# Generated by Django 4.0.1 on 2022-02-10 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppGeneral', '0001_initial'),
        ('AppProjectList', '0003_rename_datetimeendproject_projectlist_duedatetimeproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strTaskList', models.TextField(max_length=100)),
                ('dueDateTask', models.DateTimeField()),
                ('dueDateProject', models.DateTimeField()),
                ('strNotes', models.TextField(max_length=100)),
                ('strPriorty', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='AppGeneral.priorty')),
                ('strProjectName', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='AppProjectList.projectlist')),
                ('strStatus', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='AppGeneral.status')),
            ],
        ),
    ]
