# Generated by Django 4.0.1 on 2022-01-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppGeneral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strIDProject', models.TextField(max_length=20)),
                ('strProjectName', models.TextField(max_length=20)),
                ('strProjectDescription', models.TextField(max_length=100)),
                ('datetimeStartProject', models.DateTimeField()),
                ('datetimeEndProject', models.DateTimeField()),
                ('strDirectoryFolder', models.TextField(max_length=100)),
                ('strUrlDirectoryProject', models.TextField(max_length=100)),
                ('strNotes', models.TextField(max_length=100)),
                ('strPriorty', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='AppGeneral.priorty')),
                ('strStatus', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='AppGeneral.status')),
            ],
        ),
    ]
