# Generated by Django 4.0.1 on 2022-02-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProjectList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlist',
            name='strDirectoryFolder',
        ),
        migrations.RemoveField(
            model_name='projectlist',
            name='strUrlDirectoryProject',
        ),
    ]
