# Generated by Django 4.0.1 on 2022-02-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProjectList', '0002_remove_projectlist_strdirectoryfolder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectlist',
            old_name='datetimeEndProject',
            new_name='dueDateTimeProject',
        ),
    ]
