# Generated by Django 4.0.1 on 2022-04-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProjectList', '0004_alter_projectlist_datetimestartproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='strProjectName',
            field=models.TextField(max_length=100),
        ),
    ]
